trigger:
  branches:
    include:
      - main  

variables:
  imageName: ghcr.io/amansk5/nodejs-api
  tag: $(Build.BuildId)
  helmChartPath: devops-nodejsexpress/nodejs-api-chart
  namespace: nodejs

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and Push Docker image
            inputs:
              command: buildAndPush
              repository: $(imageName)
              tags: |
                $(tag)
              dockerfile: dockerfile
              containerRegistry: GHCRConnection

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: Build
    jobs:
      - deployment: DeployToAKS
        environment: aks-nodejs
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  displayName: Set Kubernetes context
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'AKSConnection'
                    namespace: $(namespace)
                    command: 'login'   # Ensures it only authenticates, no cluster queries
                    arguments: ''

                - task: HelmInstaller@1
                  displayName: Install Helm
                  inputs:
                    helmVersionToInstall: 'latest'

                - script: |
                    helm upgrade --install nodejs-api $(helmChartPath) \
                      --namespace $(namespace) \
                      --set image.repository=$(imageName) \
                      --set image.tag=$(tag)
                  displayName: Helm Upgrade
