trigger:
  branches:
    include:
      - main  

variables:
  imageName: ghcr.io/amansk5/nodejs-api
  tag: $(Build.BuildId)
  helmChartPath: ./nodejs-api-chart  # Assuming the chart is inside the 'nodejs-api-chart' directory in the repo
  namespace: nodejs

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: buildAndPush
              repository: $(imageName)
              tags: |
                $(tag)
              dockerfile: dockerfile
              containerRegistry: GHCRConnection

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: Build
    jobs:
      - deployment: DeployToAKS
        environment: aks-nodejs
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                # Explicit checkout to ensure the repository is fetched
                - checkout: self  # Ensure the repository is checked out

                - task: AzureCLI@2
                  displayName: 'Set AKS context'
                  inputs:
                    azureSubscription: 'AzureSubscriptionConnection'  # Use the correct AzureRM service connection
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az aks get-credentials --resource-group devops-aks-resource-group --name devops-aks-cluster --overwrite-existing

                - task: HelmInstaller@1
                  displayName: Install Helm
                  inputs:
                    helmVersionToInstall: 'latest'

                - script: |
                    echo "Validating Kubernetes context..."
                    kubectl config current-context
                    kubectl get pods -n $(namespace)
                  displayName: Validate Kubernetes context

                # Listing files in the repository to check the structure
                - script: |
                    echo "Listing files in the repository..."
                    ls -R /home/vsts/work/1/s/  # List files in the root of the repository for debugging
                  displayName: 'List all files in the repository'

                # Helm upgrade
                - script: |
                    helm upgrade --install nodejs-api $(helmChartPath) \
                      --namespace $(namespace) \
                      --set image.repository=$(imageName) \
                      --set image.tag=$(tag)
                  displayName: Helm Upgrade
