replicaCount: 1

image:
  repository: ghcr.io/amansk5/nodejs-api
  tag: "{{ .Chart.AppVersion }}"  # Uses Helm's Chart versioning
  pullPolicy: Always  # Ensures the image is always pulled

env:
  DBNAME: "{{ .Values.env.DBNAME }}"
  MONGOURI: "{{ .Values.env.MONGOURI }}"
  PORT: "{{ .Values.env.PORT }}"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 3000

containerPort: 3000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true

serviceAccount:
  create: false

ingress:
  enabled: false  # Change to true if you want to enable ingress
  className: "nginx"
  annotations: {}
  hosts:
    - host: nodejs.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false  # Change to true if you want HPA
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []
