replicaCount: 1

image:
  repository: nodejs-api
  tag: latest

containerPort: 3000

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: false

ingress:
  enabled: false  # Disable ingress

autoscaling:
  enabled: false  # Disable autoscaling (or set to true if you want to enable it)
