replicaCount: 1

image:
  repository: ghcr.io/amansk5/nodejs-api
  tag: "{{ .Values.image.tag }}"
  pullPolicy: Always  # Ensures the image is always pulled

env:
  DBNAME: ""
  MONGOURI: ""
  PORT: ""

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 3000

containerPort: 3000

serviceAccount:
  create: false

ingress:
  enabled: false  # Change to true if you want to enable ingress
  className: "nginx"
  annotations: {}
  hosts:
    - host: nodejs.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false  # Change to true if you want HPA
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
