replicaCount: 1

image:
  repository: ghcr.io/amansk5/nodejs-api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 3000

containerPort: 3000

serviceAccount:
  create: false

env:
  DBNAME: ""
  MONGOURI: ""
  PORT: ""

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: nodejs.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
